# Import the Library

In [2]:
import numpy as np
from numpy import array
from numpy.linalg import eig, inv

# Soal

Apakah [1, 3] adalah eigen vector dari [1, −1, 6, 4]? 

Jika Iya, berapakah eigen value-nya?


In [5]:
# pendefinisian vector a

a = [[1, -1],
     [6, 4]]

matrix_a = np.array(a)
print(matrix_a)

[[ 1 -1]
 [ 6  4]]


In [6]:
# eigen value & eigen vector

e_val, e_vec = eig(matrix_a)

In [7]:
# eigen vector dari matrix a

e_vec

array([[ 0.23145502-0.29880715j,  0.23145502+0.29880715j],
       [-0.9258201 +0.j        , -0.9258201 -0.j        ]])

Jadi, eigen vector dari matrix a adalah bukan [1, 3].

In [9]:
# eigen value dari matrix a

e_val

array([2.5+1.93649167j, 2.5-1.93649167j])