# Import library

In [1]:
import numpy as np

# Soal 1
Buatlah vektor di bawah ini dengan Python: 

(17, 22, 19)


In [2]:
a = [17, 22, 19]
vect_a = np.array(a)
vect_a

array([17, 22, 19])

# Soal 2
Diberikan3 buah vector 3 dimensi: 𝑨=17, 22, 19, 𝑩=10, 20, 11, 𝑪=5, 12, 9

Hitunglah:
1. A+B
2. B-C
3. A dot C
4. A x B
5. norm A
6. Sudut antara vektor A dan B


In [3]:
A = [17,22, 19]
vect_A = np.array(A)
vect_A

array([17, 22, 19])

In [4]:
B = [10, 20, 11]
vect_B = np.array(B)
vect_B

array([10, 20, 11])

In [5]:
C = [5, 12, 9]
vect_C = np.array(C)
vect_C

array([ 5, 12,  9])

## A + B

In [7]:
print('Penjumlahan', vect_A + vect_B)

Penjumlahan [27 42 30]


## B - C

In [8]:
print('Pengurangan', vect_B - vect_C)

Pengurangan [5 8 2]


## A dot C

In [10]:
print(np.dot(vect_A, vect_C))

520


## A x B

In [11]:
print('Perkalian', vect_A * vect_B)

Perkalian [170 440 209]


## norm A

In [12]:
# Manhattan Distance

print('Manhattan Distance')
print(np.linalg.norm(vect_A, 1))
print(' ')

Manhattan Distance
58.0
 


In [14]:
# Euclidean Distance

print('Euclidean Distance')
print(np.linalg.norm(vect_A))

Euclidean Distance
33.67491648096547


## Sudut antara vektor A dan B

In [15]:
# A & B are two vectors and θ is the angle between two vectors A and B.

cos_theta = (vect_A @ vect_B) / (np.linalg.norm(vect_A) * np.linalg.norm(vect_B))
cos_theta

0.9759590023331435