# Import the Library

In [1]:
import numpy as np

# 1. Perkalian Matrix

In [3]:
A = [[23, 50, 19],
     [7, 12, 109],
     [57, 67, 98]]

matrix_A = np.array(A)
print(matrix_A)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


In [4]:
B = [[17],
     [22],
     [19]]

matrix_B = np.array(B)
print(matrix_B)

[[17]
 [22]
 [19]]


In [5]:
# Perkalian A dan B

print(matrix_A * matrix_B)

[[ 391  850  323]
 [ 154  264 2398]
 [1083 1273 1862]]


# 2. Hitung Transpose, Determinan, dan Inverse

In [6]:
C = [[23, 50, 19],
     [7, 12, 109],
     [57, 67, 98]]

matrix_C = np.array(C)
print(matrix_C)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


In [14]:
# Transpose C

np.transpose(matrix_C)

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [10]:
# Determinant C

print('Determinant of Matrix C is', np.linalg.det(matrix_C))

Determinant of Matrix C is 131344.0000000002


In [17]:
# Inverse C

np.linalg.inv(matrix_C)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])